---
- name: interface config
  hosts: switch_cisco
  gather_facts: no
  tasks:
    - name: action interface trunk config
      ios_config:
        lines:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - no shutdown
        parents: interface range GigabitEthernet 0/1-3

    - name: save configuration
      ios_command:
        write

    - name: backup cisco_switch_cisco config
      ios_config:
        backup:
          true


